/* Figures 11–15 */
(function () {
  "use strict";
  var L = window.LTA, H = L.H, C = L.C, reg = L.reg;

  function svg(vb, body, h) {
    return '<svg viewBox="' + vb + '" width="100%" height="' + (h || 440) +
      '" preserveAspectRatio="xMidYMid meet" role="img" xmlns="http://www.w3.org/2000/svg" ' +
      'font-family="IBM Plex Mono, ui-monospace, monospace">' + body + "</svg>";
  }
  function txt(x, y, s, o) {
    o = o || {};
    return '<text x="' + x + '" y="' + y + '" fill="' + (o.fill || C.ink) + '" font-size="' + (o.size || 11) +
      '" text-anchor="' + (o.anchor || "start") + '" opacity="' + (o.op === undefined ? 1 : o.op) +
      '"' + (o.ls ? ' letter-spacing="' + o.ls + '"' : "") + ">" + H.esc(s) + "</text>";
  }
  function rect(x, y, w, h2, o) {
    o = o || {};
    return '<path d="' + H.box(x, y, Math.max(0, w), Math.max(0, h2), o.r === undefined ? 3 : o.r) +
      '" fill="' + (o.fill || "none") + '" stroke="' + (o.stroke || C.line) + '" stroke-width="' + (o.sw || 1) +
      '" opacity="' + (o.op === undefined ? 1 : o.op) + '"' + (o.dash ? ' stroke-dasharray="' + o.dash + '"' : "") + "/>";
  }
  function chip(x, y, w, h2, label, col, op, fo) {
    return rect(x, y, w, h2, { stroke: col, fill: col, op: (fo === undefined ? 0.13 : fo) * (op === undefined ? 1 : op) }) +
      rect(x, y, w, h2, { stroke: col, op: op }) +
      txt(x + w / 2, y + h2 / 2 + 4, label, { anchor: "middle", fill: col, size: 10.5, op: op });
  }

  /* ===================== FIGURE 11 — the rollout engine =================== */
  reg("fig-rollout", {
    total: 12, rate: 0.58,
    captions: [
      "Eight rollouts launched together. Each one is an agent talking to a real environment.",
      "They do not take the same time. Trajectory lengths differ, and so do tool latencies.",
      "The quick ones are done in a fraction of the batch time.",
      "One of them is a forty-turn trajectory against a slow API.",
      "In a synchronous loop, the optimiser cannot start until it lands.",
      "Everything shaded is accelerator time bought and not used.",
      "The utilisation ceiling is set by the mean over the maximum \u2014 and heavy tails make that ratio small.",
      "Asynchronous rollout: each worker starts a new episode the moment it finishes one.",
      "Finished trajectories drop into a queue instead of into a barrier.",
      "The trainer consumes from the queue continuously. The bubble is gone.",
      "The cost is staleness \u2014 the data was generated by an older policy version than the one being updated.",
      "So the algorithm has to absorb off-policy data. Importance-ratio correction and a bounded staleness window are what buy the throughput."
    ],
    params: [{ key: "tail", label: "duration spread \u03c3", min: 0.15, max: 1.3, step: 0.05, value: 0.7, fmt: function (v) { return H.fmt(v, 2); } }],
    render: function (t, p) {
      var b = rect(0, 0, 900, 440, { fill: C.bg, stroke: "none", r: 0 });
      var N = 8, rnd = H.rnd(23), durs = [];
      for (var i = 0; i < N; i++) {
        var u1 = Math.max(1e-6, rnd()), u2 = rnd();
        var g = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
        durs.push(Math.exp(g * p.tail));
      }
      var mx = Math.max.apply(null, durs), mean = durs.reduce(function (a, c) { return a + c; }, 0) / N;
      var util = mean / mx;
      var scale = 300 / mx;

      /* synchronous */
      b += txt(40, 34, "SYNCHRONOUS BATCH", { fill: C.dim, size: 10, ls: 1.8 });
      var t1 = H.clamp(H.segE(t, 1) * 0.4 + H.segE(t, 2) * 0.3 + H.segE(t, 3) * 0.3, 0, 1);
      for (var r = 0; r < N; r++) {
        var y = 50 + r * 22;
        b += rect(46, y, 300, 14, { fill: C.grid, stroke: "none", r: 2 });
        var w = durs[r] * scale * (t < 1 ? H.segE(t, 0) * 0.35 : t1);
        var isStrag = durs[r] === mx;
        b += rect(46, y, Math.min(w, durs[r] * scale), 14, { fill: isStrag ? C.amber : C.blue, stroke: "none", r: 2, op: 0.7 });
        if (H.segE(t, 5) > 0.02 && w >= durs[r] * scale - 0.5) {
          b += rect(46 + durs[r] * scale, y, (mx - durs[r]) * scale, 14,
            { fill: C.red, stroke: "none", r: 2, op: 0.22 * H.segE(t, 5) });
        }
      }
      var a3 = H.segE(t, 3);
      b += txt(46 + mx * scale + 8, 50 + 14, "straggler", { fill: C.amber, size: 9.5, op: a3 });
      var a4 = H.segE(t, 4);
      b += '<path d="' + H.poly([[46 + mx * scale, 44], [46 + mx * scale, 232]]) + '" stroke="' + C.red +
        '" stroke-width="1.4" stroke-dasharray="4 3" opacity="' + a4 + '"/>';
      b += txt(46 + mx * scale + 8, 240, "barrier \u2192 optimiser step", { fill: C.red, size: 9.5, op: a4 });
      var a6 = H.segE(t, 6);
      b += rect(40, 254, 320, 62, { fill: C.panel, stroke: C.line, op: a6 });
      b += txt(58, 278, "utilisation \u2264 E[T] / E[max\u1d62 T\u1d62]", { fill: C.red, size: 12, op: a6 });
      b += txt(58, 300, "here: " + Math.round(util * 100) + "%   \u2014 raise \u03c3 and watch it fall", { fill: C.dim, size: 10, op: a6 });

      /* asynchronous */
      var a7 = H.segE(t, 7);
      b += txt(470, 34, "ASYNCHRONOUS", { fill: C.dim, size: 10, ls: 1.8, op: a7 });
      var flow = H.clamp(H.segE(t, 7) * 0.4 + H.segE(t, 8) * 0.3 + H.segE(t, 9) * 0.3, 0, 1);
      for (var r2 = 0; r2 < N; r2++) {
        var y2 = 50 + r2 * 22, cursor = 0, seg = 0, rn = H.rnd(31 + r2);
        b += rect(476, y2, 300, 14, { fill: C.grid, stroke: "none", r: 2 });
        while (cursor < 300 * flow && seg < 8) {
          var u1b = Math.max(1e-6, rn()), u2b = rn();
          var gb = Math.sqrt(-2 * Math.log(u1b)) * Math.cos(2 * Math.PI * u2b);
          var d = Math.exp(gb * p.tail) * scale;
          var wseg = Math.min(d - 3, 300 * flow - cursor);
          if (wseg > 1) b += rect(476 + cursor, y2, wseg, 14, { fill: C.green, stroke: "none", r: 2, op: 0.62 });
          cursor += d; seg++;
        }
      }
      /* the sorting rule, stated once, in the space above the action row */
      var a1 = H.segE(t, 1);
      var rule = [
        ["reversible", "env.reset() or an inverse action restores the state", C.green],
        ["costly", "an inverse exists, but paying for it is the whole task", C.amber],
        ["irreversible", "no action in the set returns the world to where it was", C.red]
      ];
      b += txt(40, 62, "SORTED BY WHETHER AN INVERSE EXISTS", { fill: C.dim, size: 9, ls: 1.6, op: a1 });
      rule.forEach(function (r, i) {
        b += rect(40, 76 + i * 26, 9, 9, { fill: r[2], stroke: "none", r: 2, op: a1 });
        b += txt(58, 85 + i * 26, r[0], { fill: r[2], size: 10, op: a1 });
        b += txt(158, 85 + i * 26, r[1], { fill: C.faint, size: 9.5, op: a1 });
      });

      var a8 = H.segE(t, 8);
      b += rect(790, 46, 70, 186, { stroke: C.teal, fill: C.teal, op: 0.1 * a8, r: 3 });
      b += rect(790, 46, 70, 186, { stroke: C.teal, op: a8 });
      b += txt(825, 66, "queue", { anchor: "middle", fill: C.teal, size: 9.5, op: a8 });
      for (var qq = 0; qq < 7; qq++) {
        b += rect(798, 78 + qq * 20, 54, 13, { fill: C.green, stroke: "none", r: 2, op: 0.5 * a8 * H.clamp(a8 * 3 - qq * 0.25, 0, 1) });
      }
      var a9 = H.segE(t, 9);
      b += rect(470, 254, 390, 62, { fill: C.panel, stroke: C.line, op: a9 });
      b += txt(488, 278, "trainer consumes continuously \u2014 no barrier", { fill: C.green, size: 11.5, op: a9 });
      var a10 = H.segE(t, 10);
      b += txt(488, 300, "policy versions in flight: \u03b8\u209c\u208b\u2083 \u2026 \u03b8\u209c", { fill: C.amber, size: 10.5, op: a10 });

      var a11 = H.segE(t, 11);
      b += rect(40, 336, 820, 82, { fill: C.panel, stroke: C.line, op: a11 });
      b += txt(58, 362, "\u2207J  \u2248  E\u209c~\u03c0_old [  ( \u03c0\u03b8(a|s) / \u03c0_old(a|s) ) \u00b7 A(s, a)  ]      with  age(\u03c4) \u2264 k", { fill: C.green, size: 12.5, op: a11 });
      b += txt(58, 386, "Throughput and on-policyness trade against each other directly. A bounded staleness window k is the knob:", { fill: C.dim, size: 10, op: a11 });
      b += txt(58, 404, "k = 0 is synchronous and idle; k large is fast and unstable. Most production agent-RL stacks sit at small k.", { fill: C.dim, size: 10, op: a11 });
      return svg("0 0 900 440", b);
    }
  });

  /* ===================== FIGURE 12 — context as a resource ================ */
  reg("fig-context", {
    total: 12, rate: 0.6,
    captions: [
      "The context window at the start of an episode. Almost all of it is free.",
      "Turn one: a thought, a tool call, and a tool result.",
      "Turn two. Note which part is growing fastest.",
      "It is not the reasoning. It is the observations \u2014 page dumps, file contents, stack traces.",
      "By turn twelve the budget is more than half spent on things the agent has already finished using.",
      "Turn twenty. The window overflows and the oldest tokens go first \u2014 which is where the goal was written.",
      "So the agent is now optimising a task it can no longer read. Long-horizon failure often looks like this rather than like bad reasoning.",
      "The alternative: run a sub-task in a branch with its own context.",
      "The branch does its exploring in private.",
      "Then fold: discard the branch's transcript and keep only what the main thread needs.",
      "The main context stays small while the total work done grows with the number of branches.",
      "Effective horizon becomes a function of how well the policy compresses, which makes compression itself a learnable action."
    ],
    render: function (t) {
      var b = rect(0, 0, 900, 440, { fill: C.bg, stroke: "none", r: 0 });
      var bx = 40, by = 56, bw = 380, bh = 300;
      b += txt(40, 34, "LINEAR CONTEXT  (ReAct)", { fill: C.dim, size: 10, ls: 1.8 });
      b += rect(bx, by, bw, bh, { stroke: C.line, fill: C.panel });
      b += txt(bx + 8, by + 16, "goal", { fill: C.amber, size: 9.5 });
      b += rect(bx + 6, by + 22, bw - 12, 14, { fill: C.amber, stroke: "none", op: 0.5, r: 2 });

      var turns = Math.round(H.clamp(H.segE(t, 1) * 2 + H.segE(t, 2) * 3 + H.segE(t, 3) * 4 +
        H.segE(t, 4) * 6 + H.segE(t, 5) * 7, 0, 22));
      var yCur = by + 42, over = false;
      for (var i = 0; i < turns; i++) {
        var think = 8, obs = 14 + (i % 3) * 6;
        if (yCur + think + obs > by + bh - 6) { over = true; break; }
        b += rect(bx + 6, yCur, (bw - 12) * 0.55, think, { fill: C.blue, stroke: "none", op: 0.55, r: 2 });
        yCur += think + 2;
        b += rect(bx + 6, yCur, bw - 12, obs, { fill: C.teal, stroke: "none", op: 0.35 + (H.segE(t, 3) * 0.3), r: 2 });
        yCur += obs + 3;
      }
      b += txt(bx + 8, by + bh + 18, "thought", { fill: C.blue, size: 9 });
      b += txt(bx + 78, by + bh + 18, "observation", { fill: C.teal, size: 9 });
      var a3 = H.segE(t, 3);
      b += txt(bx + bw - 6, by + bh + 18, "observations dominate", { fill: C.teal, size: 9, anchor: "end", op: a3 });

      var a5 = H.segE(t, 5);
      if (over || a5 > 0.4) {
        b += rect(bx, by, bw, bh, { stroke: C.red, sw: 1.6, op: a5 });
        b += rect(bx + 6, by + 22, bw - 12, 14, { fill: C.red, stroke: "none", op: 0.55 * a5, r: 2 });
        b += txt(bx + bw / 2, by + 33, "evicted", { anchor: "middle", fill: C.bg, size: 9, op: a5 });
      }
      var a6 = H.segE(t, 6);
      b += txt(bx, by + bh + 38, "the goal was the oldest thing in the window", { fill: C.red, size: 10, op: a6 });

      /* folding */
      var a7 = H.segE(t, 7);
      b += txt(470, 34, "BRANCH AND FOLD", { fill: C.dim, size: 10, ls: 1.8, op: a7 });
      var mx2 = 470, mw = 150;
      b += rect(mx2, by, mw, bh, { stroke: C.line, fill: C.panel, op: a7 });
      b += txt(mx2 + 8, by + 16, "main", { fill: C.dim, size: 9, op: a7 });
      b += rect(mx2 + 6, by + 22, mw - 12, 14, { fill: C.amber, stroke: "none", op: 0.5 * a7, r: 2 });

      var a8 = H.segE(t, 8), a9 = H.segE(t, 9), a10 = H.segE(t, 10);
      for (var br = 0; br < 3; br++) {
        var bshow = [a8, a9 * 0.9, a10][br];
        var byy = by + 46 + br * 92;
        b += rect(660, byy, 190, 78, { stroke: C.purple, fill: C.purple, op: 0.08 * bshow, r: 3 });
        b += rect(660, byy, 190, 78, { stroke: C.purple, op: bshow, dash: "3 3" });
        b += txt(670, byy + 18, "branch " + (br + 1), { fill: C.purple, size: 9.5, op: bshow });
        for (var q = 0; q < 4; q++) {
          b += rect(668, byy + 26 + q * 12, 174 - q * 8, 9, { fill: C.teal, stroke: "none", op: 0.4 * bshow, r: 2 });
        }
        var fold = [a9, a10, a10 * 0.8][br];
        b += H.arrow(658, byy + 40, mx2 + mw + 6, byy + 40, C.green, 1.4, fold);
        b += rect(mx2 + 6, by + 52 + br * 30, mw - 12, 20, { fill: C.green, stroke: "none", op: 0.45 * fold, r: 2 });
        b += txt(mx2 + 12, by + 66 + br * 30, "result " + (br + 1), { fill: C.bg, size: 9, op: fold });
      }
      b += txt(660, by + bh + 18, "discarded after folding", { fill: C.purple, size: 9, op: a10 });

      var a11 = H.segE(t, 11);
      b += rect(40, 386, 820, 44, { fill: C.panel, stroke: C.line, op: a11 });
      b += txt(58, 412, "effective work  \u2248  k branches \u00d7 B tokens,   resident context  \u2248  B  \u2014 if the fold is lossless enough to act on", { fill: C.green, size: 11.5, op: a11 });
      return svg("0 0 900 440", b);
    }
  });

  /* ===================== FIGURE 13 — irreversibility ===================== */
  reg("fig-irreversible", {
    total: 10, rate: 0.55,
    captions: [
      "A realistic action set for a working agent. Nothing exotic \u2014 read, write, call, send.",
      "Sort them by one property that no reasoning benchmark ever has to think about: can this be undone?",
      "Reads are free. Exploration here costs latency and nothing else.",
      "Local writes are cheap to undo. Sandboxes and git give you an exact inverse.",
      "External writes are undoable in principle and awkward in practice.",
      "And some actions have no inverse at all. The email has been read; the payment has cleared.",
      "RL requires trying things. That is not a bug in the method, it is the method.",
      "So a rollout that samples delete_production() cannot be recovered by calling reset().",
      "The fix is environmental, not behavioural: a twin to explore in, a staging layer to accumulate effects, and a confirmation gate on the crossing.",
      "Reversibility is a property of the environment you build. Design it before you turn exploration on."
    ],
    render: function (t) {
      var b = rect(0, 0, 900, 440, { fill: C.bg, stroke: "none", r: 0 });
      var acts = [
        { n: "read_file()", r: 0.02, s: 2 }, { n: "search(q)", r: 0.04, s: 2 }, { n: "list_dir()", r: 0.03, s: 2 },
        { n: "write_file()", r: 0.28, s: 3 }, { n: "git commit", r: 0.24, s: 3 }, { n: "create_branch()", r: 0.3, s: 3 },
        { n: "update_row()", r: 0.58, s: 4 }, { n: "deploy(staging)", r: 0.62, s: 4 }, { n: "merge_pr()", r: 0.55, s: 4 },
        { n: "send_email()", r: 0.88, s: 5 }, { n: "charge_card()", r: 0.95, s: 5 }, { n: "drop_table()", r: 0.92, s: 5 }
      ];
      b += txt(40, 34, "ACTION SET", { fill: C.dim, size: 10, ls: 1.8 });
      var sorted = H.segE(t, 1);
      var axisY = 300;
      b += '<path d="' + H.poly([[70, axisY], [830, axisY]]) + '" stroke="' + C.line + '" stroke-width="1.4" opacity="' + sorted + '"/>';
      b += txt(70, axisY + 24, "reversible", { fill: C.green, size: 10, op: sorted });
      b += txt(830, axisY + 24, "irreversible", { fill: C.red, size: 10, anchor: "end", op: sorted });

      acts.forEach(function (a, i) {
        var gx = 70 + (i % 4) * 200, gy = 62 + Math.floor(i / 4) * 44;
        var tx = 70 + a.r * 740, ty = axisY - 34 - (i % 3) * 30;
        var u = sorted;
        var x = H.lerp(gx, tx - 60, u), y = H.lerp(gy, ty, u);
        var col = a.r < 0.15 ? C.green : (a.r < 0.4 ? C.teal : (a.r < 0.75 ? C.amber : C.red));
        var op = 0.35 + 0.65 * H.segE(t, Math.max(0, a.s - (t >= 6 ? 0 : 0)));
        if (t < 2) op = H.segE(t, 0);
        b += chip(x, y, 124, 26, a.n, col, op);
        if (u > 0.9) b += '<path d="' + H.poly([[x + 62, y + 26], [x + 62, axisY - 4]]) + '" stroke="' + col + '" stroke-width="1" stroke-dasharray="2 3" opacity="' + (0.4 * op) + '"/>';
      });

      var a7 = H.segE(t, 7);
      b += rect(560, 60, 300, 96, { fill: C.panel, stroke: C.red, op: a7 });
      b += txt(576, 84, "rollout 4 / 16", { fill: C.dim, size: 9, op: a7 });
      b += txt(576, 106, "drop_table(\u201corders\u201d)", { fill: C.red, size: 12, op: a7 });
      b += txt(576, 128, "env.reset()  \u2192  cannot restore", { fill: C.red, size: 10.5, op: a7 });
      b += txt(576, 146, "the episode ended; the effect did not", { fill: C.dim, size: 9.5, op: a7 });

      /* the sorting rule, stated once, in the space above the action row */
      var a1 = H.segE(t, 1);
      var rule = [
        ["reversible", "env.reset() or an inverse action restores the state", C.green],
        ["costly", "an inverse exists, but paying for it is the whole task", C.amber],
        ["irreversible", "no action in the set returns the world to where it was", C.red]
      ];
      b += txt(40, 62, "SORTED BY WHETHER AN INVERSE EXISTS", { fill: C.dim, size: 9, ls: 1.6, op: a1 });
      rule.forEach(function (r, i) {
        b += rect(40, 76 + i * 26, 9, 9, { fill: r[2], stroke: "none", r: 2, op: a1 });
        b += txt(58, 85 + i * 26, r[0], { fill: r[2], size: 10, op: a1 });
        b += txt(158, 85 + i * 26, r[1], { fill: C.faint, size: 9.5, op: a1 });
      });

      var a8 = H.segE(t, 8);
      b += rect(40, 336, 820, 84, { fill: C.panel, stroke: C.line, op: a8 });
      ["digital twin \u2014 explore in a copy", "staging layer \u2014 accumulate, commit once", "confirmation gate \u2014 a human approves"].forEach(function (s, i) {
        b += chip(58 + i * 270, 352, 250, 32, "", C.teal, a8, 0.08);
        b += txt(70 + i * 270, 372, s, { fill: C.teal, size: 10, op: a8 });
      });
      b += txt(58, 408, "An environment without an inverse is an environment you cannot safely run online RL in.", { fill: C.dim, size: 10, op: H.segE(t, 9) });
      return svg("0 0 900 440", b);
    }
  });

  /* ===================== FIGURE 14 — the horizon law ===================== */
  reg("fig-horizon", {
    total: 8, rate: 0.45,
    captions: [
      "Model a task as H independent decisions, each of which the agent gets right with probability q.",
      "Then end-to-end success is q^H \u2014 an exponential decay in the number of steps.",
      "The horizon at which the agent succeeds half the time has a closed form.",
      "Move the slider. Reliability improvements that look tiny per step move the horizon a long way.",
      "Because doubling the horizon requires halving \u2212ln q, which for q near one means roughly halving the per-step error.",
      "Empirically, the length of task frontier agents finish at fifty percent reliability has been climbing on a roughly exponential trend.",
      "But the same curve tells you the eighty- and ninety-nine-percent horizons are much shorter, and shipping usually needs those.",
      "The constant-hazard model is a simplification: real tasks have correlated failures, recoverable errors, and steps that matter far more than others. It is a lens, not a law."
    ],
    params: [{ key: "q", label: "per-step reliability q", min: 0.900, max: 0.9995, step: 0.0005, value: 0.985, fmt: function (v) { return H.fmt(v, 4); } }],
    render: function (t, p) {
      var b = rect(0, 0, 900, 440, { fill: C.bg, stroke: "none", r: 0 });
      var q = p.q;
      var H50 = Math.log(0.5) / Math.log(q), H80 = Math.log(0.8) / Math.log(q), H99 = Math.log(0.99) / Math.log(q);

      var px = 40, py = 52, pw = 420, ph = 268;
      b += rect(px, py, pw, ph, { stroke: C.line, fill: C.panel });
      b += txt(px + 12, py + 18, "P(success)  =  q^H", { fill: C.dim, size: 9.5, ls: 1.2 });
      b += txt(px + pw / 2, py + ph + 16, "task length H (log)", { fill: C.faint, size: 9, anchor: "middle" });
      var X = function (h) { return px + 36 + (Math.log(Math.max(1, h)) / Math.log(3000)) * (pw - 58); };
      var Y = function (v) { return py + ph - 30 - v * (ph - 60); };
      var a1 = H.segE(t, 1);
      var cur = [];
      for (var h = 1; h <= 3000; h *= 1.09) cur.push([X(h), Y(Math.pow(q, h))]);
      var n1 = Math.max(2, Math.round(cur.length * H.clamp(a1 * 1.2, 0, 1)));
      b += '<path d="' + H.curve(cur.slice(0, n1)) + '" stroke="' + C.green + '" stroke-width="2.2" fill="none"/>';
      [[0.5, C.amber, "50%"], [0.8, C.blue, "80%"], [0.99, C.pink, "99%"]].forEach(function (lv, i) {
        var op = H.segE(t, i === 0 ? 2 : 6);
        b += '<path d="' + H.poly([[px + 36, Y(lv[0])], [px + pw - 22, Y(lv[0])]]) + '" stroke="' + lv[1] +
          '" stroke-width="1" stroke-dasharray="3 3" opacity="' + (0.6 * op) + '"/>';
        var hh = Math.log(lv[0]) / Math.log(q);
        b += '<path d="' + H.poly([[X(hh), Y(lv[0])], [X(hh), Y(0)]]) + '" stroke="' + lv[1] + '" stroke-width="1" stroke-dasharray="3 3" opacity="' + (0.6 * op) + '"/>';
        b += txt(X(hh) + 7, Y(lv[0]) + 13, lv[2] + " @ " + Math.round(hh), { fill: lv[1], size: 9.5, op: op });
      });
      [1, 10, 100, 1000].forEach(function (h2) {
        b += txt(X(h2), py + ph - 14, String(h2), { fill: C.faint, size: 8.5, anchor: "middle" });
      });

      var a2 = H.segE(t, 2);
      b += rect(486, 52, 374, 118, { fill: C.panel, stroke: C.line, op: a2 });
      b += txt(504, 82, "H\u2085\u2080  =  ln(0.5) / ln(q)  =  " + H.fmt(H50, 1) + " steps", { fill: C.green, size: 14, op: a2 });
      b += txt(504, 112, "H\u2088\u2080 = " + H.fmt(H80, 1) + "     H\u2089\u2089 = " + H.fmt(H99, 1), { fill: C.dim, size: 11.5, op: H.segE(t, 6) });
      b += txt(504, 140, "q = " + H.fmt(q, 4) + "   \u2192   per-step error " + H.fmt((1 - q) * 100, 2) + "%", { fill: C.amber, size: 11, op: a2 });
      b += txt(504, 158, "halving that error doubles H\u2085\u2080", { fill: C.dim, size: 10, op: H.segE(t, 4) });

      /* trend panel */
      var a5 = H.segE(t, 5);
      var tx = 486, ty = 186, tw = 374, th = 134;
      b += rect(tx, ty, tw, th, { stroke: C.line, fill: C.panel, op: a5 });
      b += txt(tx + 12, ty + 18, "SCHEMATIC: H\u2085\u2080 OVER TIME", { fill: C.dim, size: 9, ls: 1.3, op: a5 });
      var tp = [];
      for (var u = 0; u <= 40; u++) {
        tp.push([tx + 26 + (u / 40) * (tw - 46), ty + th - 24 - (u / 40) * (th - 48)]);
      }
      b += '<path d="' + H.curve(tp) + '" stroke="' + C.blue + '" stroke-width="2" fill="none" opacity="' + a5 + '"/>';
      for (var d = 0; d < 5; d++) {
        b += '<circle cx="' + H.fmt(tp[d * 9][0], 1) + '" cy="' + H.fmt(tp[d * 9][1], 1) + '" r="3.4" fill="' + C.blue + '" opacity="' + a5 + '"/>';
      }
      b += txt(tx + 26, ty + th - 8, "2019", { fill: C.faint, size: 8.5, op: a5 });
      b += txt(tx + tw - 18, ty + th - 8, "2026", { fill: C.faint, size: 8.5, anchor: "end", op: a5 });
      b += txt(tx + 34, ty + 40, "log scale on the vertical axis", { fill: C.faint, size: 9, op: a5 });

      var a7 = H.segE(t, 7);
      b += rect(40, 340, 820, 78, { fill: C.panel, stroke: C.line, op: a7 });
      b += txt(58, 366, "Treat this as a lens, not a law. Real trajectories have recoverable errors, correlated failures, and a few steps that carry", { fill: C.dim, size: 10, op: a7 });
      b += txt(58, 384, "most of the risk. A model that can retry turns one hard step into several easy ones \u2014 which is exactly the capability", { fill: C.dim, size: 10, op: a7 });
      b += txt(58, 402, "interactive training is supposed to install, and exactly what the independence assumption above throws away.", { fill: C.dim, size: 10, op: a7 });
      return svg("0 0 900 440", b);
    }
  });

  /* ===================== FIGURE 15 — the training stack ================== */
  reg("fig-stack", {
    total: 10, rate: 0.55,
    captions: [
      "Start from a capable base model. Nothing here trains an agent from scratch.",
      "Behavioural cloning on demonstrations installs the syntax: what an action looks like, how a tool call is shaped.",
      "Early experience adds the agent's own consequences as supervision, with no reward function required.",
      "The environment suite is the substrate. Everything downstream is bounded by what these worlds can express and check.",
      "Verifiers turn environment state into reward: tests, database queries, file diffs, rubric judges where nothing executable exists.",
      "Online RL with a horizon curriculum and difficulty filtering, so batches keep carrying signal.",
      "A credit-assignment scheme finer than the trajectory, because outcome-only advantage is too noisy at this length.",
      "Asynchronous rollout infrastructure, because the environment is now on the critical path of every optimiser step.",
      "Evaluation on both outcome and process \u2014 success rate, but also steps, cost, recovery, and safety violations.",
      "And deployment traces feed back into the environment suite. The flywheel is the point."
    ],
    render: function (t) {
      var b = rect(0, 0, 900, 440, { fill: C.bg, stroke: "none", r: 0 });
      var rows = [
        ["base model", C.faint], ["behavioural cloning", C.blue], ["early experience", C.teal],
        ["environment suite", C.purple], ["verifiers & rewards", C.pink], ["online RL + curriculum", C.green],
        ["step-level credit", C.amber], ["async rollout engine", C.blue], ["outcome + process eval", C.teal],
        ["deployment traces", C.green]
      ];
      rows.forEach(function (r, i) {
        var op = H.segE(t, i);
        var y = 40 + i * 36;
        var w = 320 + i * 26;
        b += rect(60, y, w, 28, { stroke: r[1], fill: r[1], op: 0.12 * op, r: 3 });
        b += rect(60, y, w, 28, { stroke: r[1], op: op });
        b += txt(74, y + 19, String(i + 1).padStart(2, "0") + "   " + r[0], { fill: r[1], size: 11.5, op: op });
        if (i > 0) b += H.arrow(70, y - 8, 70, y - 1, r[1], 1.2, op * 0.8);
      });
      var a9 = H.segE(t, 9);
      /* what each layer contributes, revealed with its row */
      var notes = ["capability and format priors", "the shape of a trajectory", "consequences, before any reward", "the dataset, in generator form", "what counts as having succeeded", "learning on its own distribution", "resolution below the episode", "throughput without a barrier", "what you are actually measuring"];
      notes.forEach(function (nt, i) {
        b += txt(634, 40 + i * 36 + 19, nt, { fill: C.faint, size: 9.5, op: 0.9 * H.segE(t, i) });
      });
      b += '<path d="' + H.poly([[60 + 320 + 9 * 26 + 10, 40 + 9 * 36 + 14], [860, 40 + 9 * 36 + 14], [860, 54], [60 + 320 + 3 * 26 + 10, 54]]) +
        '" stroke="' + C.green + '" stroke-width="1.4" fill="none" stroke-dasharray="4 3" opacity="' + a9 + '"/>';
      b += H.arrow(60 + 320 + 3 * 26 + 20, 54, 60 + 320 + 3 * 26 + 10, 54, C.green, 1.4, a9);
      b += txt(700, 44, "new environments from real failures", { fill: C.green, size: 9.5, anchor: "end", op: a9 });
      return svg("0 0 900 440", b);
    }
  });
})();
